church-management-frontend/API/HOME/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify, current_app, json, session

index_bp = Blueprint("index_bp", __name__, template_folder='templates', static_folder='static')


@index_bp.route("/", methods=["POST", "GET"])
def index():
    return render_template('home/index.html')

@index_bp.route("/member_form", methods=["POST", "GET"])
def member_register():
    return render_template('home/member_form.html')

@index_bp.route("/visitors_form", methods=["POST", "GET"])
def visitors_register():
    return render_template('home/visitors_form.html')

@index_bp.route("/workforce_form", methods=["POST", "GET"])
def workforce_register():
    return render_template('home/workforce_form.html')

church-management-frontend/API/HOME/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=\, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{{url_for('static', filename='assets/css/style.css')}}">
  <title>Document</title>
</head>
<body id="grad1">
  <header>
    <nav class="navbar bg-body-tertiary fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"><img src="{{url_for('static', filename='assets/img/rccgjp_logo.jpg')}}" height="75px" alt="Logo"></a>
        <a href="#" class="jlogo-text">JESUS PAVILION</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">More Options</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('index_bp.index') }}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://search.app/jYBzvn1pygLJbx9M8">Jesus Pavilion Website</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="https://www.jesuspavilion.org.uk/about-us/">About us</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dashboard
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{{ url_for('auth_bp.register') }}">Sign up</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('auth_bp.login') }}">Login</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Forms
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{{ url_for('index_bp.member_register') }}">Member Registration Form</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('index_bp.visitors_register') }}">First Timers Registration Form</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('index_bp.workforce_register') }}">Workforce Registration Form</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <div class="container">
    <div class="col">
      <div class="row mb-4">
        <h3>Welcome To</h3>
      </div>
      <div class="row mb-4">
        <h1>JESUS PAVILION</h1>
      </div>
      <div class="row mb-4">
        <h2> Database Center</h2>
      </div>
      <div class="row d-flex justify-content-center">
        <a href="{{ url_for('dash_bp.dashboard') }}" class="btn btn-light">Sign in</a>
      </div>
    </div>
  </div>
<footer>

</footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

church-management-frontend/API/HOME/templates/home/member_form.html
{% extends "form_layout.html" %}
{% block title %}
Member Registration Form
{% endblock %}
{% block content %}
{%block header%} MEMBERS REGISTRATION FORM {% endblock %}
    <div class="mb-3">
            <small><span class="asteric">*</span> Required </small>
        </div>
    <div class="header-two mb-3">
        <h2>PERSONAL INFORMATION</h2>
    </div>
    <form action="#" method="POST">
    
        <div class="form-group">
            <label for="first name">First Name <span class="asteric">*</span></label>
            <input type="text" id="firstname" name="firstname" placeholder="Enter your answer" required>
        </div>
        <!-- last Name -->
        <div class="form-group">
            <label for="last name">Last Name <span class="asteric">*</span></label>
            <input type="text" id="lastname" name="lastname" placeholder="Enter your answer" required>
        </div>

        <!-- Date of Birth -->
        <div class="form-group">
            <label for="dob">Date of Birth <span class="asteric">*</span></label>
            <input type="text" id="date" name="dob" placeholder="Please input date (dd/mm/yyyy)" required>
        </div>

        
        <!-- Phone No -->
        <div class="form-group">
            <label for="phone">Phone No <span class="asteric">*</span></label>
            <input type="text" id="phone" name="phone" placeholder="Number must be 11" pattern="[0-9]{11}" required>
        </div>

        <!-- Email -->
        <div class="form-group">
            <label for="email">Email <span class="asteric">*</span></label>
            <input type="email" id="email" name="email" placeholder="Please enter an email" required>
        </div>

        <!-- Address -->
        <div class="form-group">
            <label for="address-line1">Address <span class="asteric">*</span></label>
            <input type="text" id="address-line1" name="address-line1" placeholder="Street Address Line 1" required>

        </div>
    
        <!-- City -->
        <div class="form-group">
            <label for="city">City <span class="asteric">*</span></label>
            <input type="text" id="city" name="city" placeholder="Enter your answer" required>
        </div>
    
        <!-- Post Code -->
        <div class="form-group">
            <label for="postcode">Post Code <span class="asteric">*</span></label>
            <input type="text" id="postcode" name="postcode" placeholder="Please enter at most 7 characters" maxlength="7" required>
        </div>

        <!-- Occupation -->
        <div class="form-group">
            <label for="occupation"> Occupation</label>
            <input type="text" id="occupation" name="occupation" placeholder="Enter Your Answer" >
        </div>


        <div class="header-two mb-3">
            <h2>MEMBERSHIP INFORMATION</h2>
        </div>

        <!-- Date Joined Church -->
        <div class="form-group">
            <label for="date">Date Joined Church <span class="asteric">*</span></label>
            <input type="text" id="date" name="date_joined" placeholder="Please input date (dd/mm/yyyy)" required>
        </div>

        <!-- Communication Preferences -->
        <div class="form-group">
            <label>Communication Preferences <span class="asteric">*</span></label>
            <small>  How would like to be contacted?</small>
            <label><input type="radio" name="Preferences" value="emailp" required> Email</label>
            <label><input type="radio" name="Preferences" value="phonep" required> Phone</label>
            <label><input type="radio" name="Preferences" value="smsp" required> SMS</label>
        </div>

        <!-- Membership Status -->
        <div class="form-group">
            <label>Membership Status <span class="asteric">*</span></label>
            <label><input type="radio" name="membershipstatus" value="newm" required> New Member</label>
            <label><input type="radio" name="membershipstatus" value="existinm" required> Existing Member</label>
            <label><input type="radio" name="membershipstatus" value="transferm" required> Transfer Member</label>
        </div>

         <!-- name of parish -->
         <div class="form-group">
            <label for="parish-name">If Transfer Member, Enter The Name Of Parish and Year of Attendance</label>
            <input type="text" id="parish-name" name="parish-name" placeholder="Enter Your Answer(Name of Parish, YYYY)" >
        </div>

        
        <div class="header-two mb-4">
            <h2>CONSENT AND AGREEMENTS</h2>
        </div>

        <!-- Communcation Consent -->
        <div class="form-group">
            <label for="cconsent">I AGREE TO RECEIVE EMAILS,TEXT MESSAGES, AND OTHER COMMUNICATION FROM THE CHURCH <span class="asteric">*</span></label>
            <input type="text" id="cconsent" name="cconsent" placeholder="Enter Your Answer(Yes/No)" required>
        </div>

         <!-- Privacy consent-->
        <div class="form-group">
            <label for="pconsent">I CONSENT  TO STORE MY PERSONAL INFORMATION IN THE CHURCH DATABASE <span class="asteric">*</span></label>
            <input type="text" id="pconsent" name="pconsent" placeholder="Enter Your Answer(Yes/No)" required>
        </div>   

        <!-- Submit Button -->
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>

</div>


{% endblock %}
   

church-management-frontend/API/HOME/templates/home/visitors_form.html
{% extends "form_layout.html" %}
{% block title %}
Member Registration Form
{% endblock %}
{% block content %}
{%block header%} VISITORS REGISTRATION FORM {% endblock %}
        <div class="mb-3">
            <small><span class="asteric">*</span> Required </small>
        </div>
        <div class="header-two mb-3">
            <h2>PERSONAL INFORMATION</h2>
        </div>
        <form action="#" method="POST">
        
            <!-- first Name -->
            <div class="form-group">
                <label for="first name">First Name <span class="asteric">*</span></label>
                <input type="text" id="firstname" name="firstname" placeholder="Enter your answer" required>
            </div>
            <!-- last Name -->
            <div class="form-group">
                <label for="last name">Last Name <span class="asteric">*</span></label>
                <input type="text" id="lastname" name="lastname" placeholder="Enter your answer" required>
            </div>

            <!-- Date of Birth -->
            <div class="form-group">
                <label for="dob">Date of Birth <span class="asteric">*</span></label>
                <input type="text" id="date" name="dob" placeholder="Please input date (dd/mm/yyyy)" required>
            </div>

            
            <!-- Phone No -->
            <div class="form-group">
                <label for="phone">Phone No <span class="asteric">*</span></label>
                <input type="text" id="phone" name="phone" placeholder="Number must be 11" pattern="[0-9]{11}" required>
            </div>

            <!-- Email -->
            <div class="form-group">
                <label for="email">Email <span class="asteric">*</span></label>
                <input type="email" id="email" name="email" placeholder="Please enter an email" required>
            </div>

            <!-- Address -->
            <div class="form-group">
                <label for="address-line1">Address <span class="asteric">*</span></label>
                <input type="text" id="address-line1" name="address-line1" placeholder="Street Address Line 1" required>

            </div>
        
            <!-- City -->
            <div class="form-group">
                <label for="city">City <span class="asteric">*</span></label>
                <input type="text" id="city" name="city" placeholder="Enter your answer" required>
            </div>
        
            <!-- Post Code -->
            <div class="form-group">
                <label for="postcode">Post Code <span class="asteric">*</span></label>
                <input type="text" id="postcode" name="postcode" placeholder="Please enter at most 7 characters" maxlength="7" required>
            </div>

            <!-- prayer point -->
            <div class="form-group">
                <label for="prayerp">Prayer Points </label>
                <input type="text" id="prayer" name="prayer" placeholder="Enter Your Answer" >
            </div>
            
             <!-- any children? -->
             <div class="form-group">
                <label>Do You Have Any Children? <span class="asteric">*</span></label>
                <label><input type="radio" name="any-children" value="yes" required> Yes</label>
                <label><input type="radio" name="any-children" value="no" required> No</label>
            </div>

            <!-- year attended -->
            <div class="form-group">
                <label for="year-attended">If Yes, State Name and Dob</label>
                <input type="text" id="year-attended" name="year-attended" placeholder=" Please enter name of child & dob">
            </div>
            
            <!-- Submit Button -->
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
    
   {% endblock %}

church-management-frontend/API/HOME/templates/home/workforce_form.html
{% extends "form_layout.html" %}
{% block title %}
Member Registration Form
{% endblock %}
{% block content %}
{%block header%} WORKFORCE REGISTRATION FORM {% endblock %}
        <div class="mb-3">
            <small><span class="asteric">*</span> Required </small>
        </div>
        <div class="header-two mb-3">
            <h2>PERSONAL INFORMATION</h2>
        </div>
        <form action="#" method="POST">
        
            <!-- first Name -->
            <div class="form-group">
                <label for="first name">First Name <span class="asteric">*</span></label>
                <input type="text" id="firstname" name="firstname" placeholder="Enter your answer" required>
            </div>
            <!-- last Name -->
            <div class="form-group">
                <label for="last name">Last Name <span class="asteric">*</span></label>
                <input type="text" id="lastname" name="lastname" placeholder="Enter your answer" required>
            </div>

            <!-- Date of Birth -->
            <div class="form-group">
                <label for="dob">Date of Birth <span class="asteric">*</span></label>
                <input type="text" id="date" name="dob" placeholder="Please input date (dd/mm/yyyy)" required>
            </div>

            
            <!-- Phone No -->
            <div class="form-group">
                <label for="phone">Phone No <span class="asteric">*</span></label>
                <input type="text" id="phone" name="phone" placeholder="Number must be 11" pattern="[0-9]{11}" required>
            </div>

            <!-- Email -->
            <div class="form-group">
                <label for="email">Email <span class="asteric">*</span></label>
                <input type="email" id="email" name="email" placeholder="Please enter an email" required>
            </div>

            <!-- Address -->
            <div class="form-group">
                <label for="address-line1">Address <span class="asteric">*</span></label>
                <input type="text" id="address-line1" name="address-line1" placeholder="Street Address Line 1" required>

            </div>
        
            <!-- City -->
            <div class="form-group">
                <label for="city">City <span class="asteric">*</span></label>
                <input type="text" id="city" name="city" placeholder="Enter your answer" required>
            </div>
        
            <!-- Post Code -->
            <div class="form-group">
                <label for="postcode">Post Code <span class="asteric">*</span></label>
                <input type="text" id="postcode" name="postcode" placeholder="Please enter at most 7 characters" maxlength="7" required>
            </div>

            <!-- Date Joined Church -->
            <div class="form-group">
                <label for="date">Date Joined Church <span class="asteric">*</span></label>
                <input type="text" id="date" name="date_joined" placeholder="Please input date (dd/mm/yyyy)" required>
            </div>
        
            <!-- Work force to Join -->
            <div class="form-group">
                <label>Work Force To Join <span class="asteric">*</span></label>
                <label><input type="radio" name="work-force" value="admin/usher" required> Administration/Ushering</label>
                <label><input type="radio" name="work-force" value="prayer" required> Prayer Team</label>
                <label><input type="radio" name="work-force" value="music" required> Muisic/Choir</label>
                <label><input type="radio" name="work-force" value="instrumentalists" > Instrumentalists</label>
                <label><input type="radio" name="work-force" value="media" required> Media</label>
                <label><input type="radio" name="work-force" value="children" required> Children's Team</label>
                <label><input type="radio" name="media" value="other" required> Other<input type="text" placeholder="Please input name of Workforce" ></label>
            </div>
            
             <!-- Work force training -->
             <div class="form-group">
                <label>Have You Attended Workers Training? <span class="asteric">*</span></label>
                <label><input type="radio" name="workers-training" value="yes" required> Yes</label>
                <label><input type="radio" name="workers-training" value="no" required> No</label>
            </div>
            <!-- year attended -->
            <div class="form-group">
                <label for="year-attended">If Yes, Enter The Year Attended</label>
                <input type="text" id="year-attended" name="year-attended" placeholder="Enter your answer" >
            </div>
            <!-- name of parish -->
            <div class="form-group">
                <label for="parish-name">Name of Parish</label>
                <input type="text" id="parish-name" name="parish-name" placeholder="State The Name of The Parish Attended" >
            </div>
            
            <!-- additional comment -->
            <div class="form-group">
                <label for="additional-comment">Any Additional Comment</label>
                <input type="text" id="additional-comment" name="additional-comment" placeholder="Please State Here If You Would Like To Add Any Other Comments" >
            </div>
            <!-- Submit Button -->
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
    {% endblock %}
    