church-management-frontend/API/DASH/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify, current_app, json, session

dash_bp = Blueprint("dash_bp", __name__, template_folder='templates', static_folder='static')


@dash_bp.route("/dashboard", methods=["POST", "GET"])
def dashboard():
    return render_template('dash/dashboard.html')

@dash_bp.route("/member_management", methods=["POST", "GET"])
def member():
    return render_template('dash/member.html')

church-management-frontend/API/HOME/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify, current_app, json, session

index_bp = Blueprint("index_bp", __name__, template_folder='templates', static_folder='static')


@index_bp.route("/", methods=["POST", "GET"])
def index():
    return render_template('home/index.html')

@index_bp.route("/member_form", methods=["POST", "GET"])
def member_register():
    return render_template('home/member_form.html')

@index_bp.route("/visitors_form", methods=["POST", "GET"])
def visitors_register():
    return render_template('home/visitors_form.html')

@index_bp.route("/workforce_form", methods=["POST", "GET"])
def workforce_register():
    return render_template('home/workforce_form.html')

church-management-frontend/API/MEMBERS/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify, current_app, json, session

members_bp = Blueprint("members_bp", __name__, template_folder='templates', static_folder='static')


@members_bp.route("/members", methods=["POST", "GET"])
def member_section():
    
    return render_template('member/members.html')

@members_bp.route("/add_member_form", methods=["POST", "GET"])
def admin_add():
    return render_template('member/add_member_form.html')

@members_bp.route("/view_member", methods=["POST", "GET"])
def admin_view():
    #members = Member.query.all()  # This retrieves all records from the Member table
    
    return render_template('member/view_member.html')
    # return render_template('member/view_member.html', members=members)

church-management-frontend/API/__init__.py
from flask import Flask
from flask_login import LoginManager
import os 

def create_app():
    """Initialize the core application."""
    app = Flask(__name__, instance_relative_config=False)
    app.config.from_object('config.DevConfig')

    with app.app_context():
        # Include our Routes
        from .HOME  .routes import index_bp
        from .AUTH  .routes import auth_bp
        from .DASH  .routes import dash_bp
        from .MEMBERS  .routes import members_bp

        # Register Blueprints
        app.register_blueprint(index_bp)
        app.register_blueprint(auth_bp)
        app.register_blueprint(dash_bp)
        app.register_blueprint(members_bp)
        return app
        

church-management-frontend/API/templates/form_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='assets/css/form_style.css')}}">
</head>
<body>
    <div class="form-container">
        <div class="container-head">
            <img src="{{url_for('static', filename='assets/img/rccgjp_logo.jpg')}}" height="120px" width="120px" style="left:0px; right: 0px; top: 0px; border: 0px;" alt="">
        <h1>{% block header %}{% endblock %}</h1>
        </div>
        
{% block content %}

{% endblock %}
    <script src="{{url_for('static', filename='assets/js/form.js')}}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

church-management-frontend/API/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>

    <link rel="stylesheet" href="{{url_for('static', filename='assets/css/style1.css')}}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <div class="container">
        <aside>
            <div class="top">
                <div class="logo">
                    <img src="{{url_for('static', filename='assets/img/rccgjp_logo.jpg')}}">
                    <h2 class="text-muted">Jesus <span class="danger">Pavilion</span></h2>
                </div>

                <div class="close" id="close-btn">
                    <span class="material-symbols-outlined"> close</span>
                </div>
            </div>

            <div class="sidebar">
                <a href="{{url_for('dash_bp.dashboard')}}" >
                    <span class="material-symbols-outlined">dashboard</span>
                        <h3>Dashboard</h3>
                </a>
                <a href="{{url_for('members_bp.member_section')}}" class="active">
                    <span class="material-symbols-outlined">person</span>
                        <h3>Members</h3>
                </a>
                <a href="#"><span class="material-symbols-outlined">work</span>
                        <h3>Work Force</h3>
                </a>
                <a href="#"><span class="material-symbols-outlined"> groups</span>
                        <h3>Visitors</h3>
                </a>
                <a href="#"><span class="material-symbols-outlined">show_chart</span>
                        <h3>Analytics</h3>
                </a>
                <a href="#"><span class="material-symbols-outlined">notifications</span>
                    <h3>Notifications</h3>
                    <span class="message-count">26</span>
                </a>
                <a href="#"><span class="material-symbols-outlined">settings</span>
                        <h3>Settings</h3>
                </a>
                <a href="{{url_for('index_bp.index')}}"><span class="material-symbols-outlined">logout</span>
                        <h3>Logout</h3>
                </a>
            </div>
        </aside>       
        <!-- END OF ASIDE -->
         
    {% block content %}

    {% endblock %}
    <!-- TOP RIGHT START -->
    <div class="right">
        <div class="top">
            <button id="menu-btn">
                <span class="material-symbols-outlined">menu</span>
            </button>
            <div class="theme-toggler">
                <span class="material-symbols-outlined active">light_mode</span>
                <span class="material-symbols-outlined">dark_mode</span>
            </div>
            <div class="profile">
                <div class="info">
                    <p>Hey, <b>Daniel</b></p>
                    <small class="text-muted">Admin</small>
                </div>
                <div class="profile-photo">
                    <img src="{{ url_for('static', filename='assets/img/images.jpeg') }}" alt="profile2">
                </div>
            </div>
        </div>
        <!-- END OF TOP RIGHT -->
        <div class="recent-updates">
            <h2>Notifications</h2>
            <div class="updates">
                <div class="update">
                    <div class="profile-photo">
                        <img src="{{ url_for('static', filename='assets/img/images.jpeg') }}" alt="profile2">
                    </div>
                    <div class="message">
                        <p><b>Mike Ofe</b> Signed for workforce usherstraining</p>
                        <small class="text-muted">2 Minutes ago</small>
                    </div>
                </div>

                <div class="update">
                    <div class="profile-photo">
                        <img src="{{ url_for('static', filename='assets/img/images.jpeg') }}" alt="profile2">
                    </div>
                    <div class="message">
                        <p><b>Mike Ofe</b> Signed for workforce usherstraining</p>
                        <small class="text-muted">2 Minutes ago</small>
                    </div>
                </div>
                <div class="update">
                    <div class="profile-photo">
                        <img src="#" alt="profile2">
                    </div>
                    <div class="message">
                        <p><b>Mike Ofe</b> Signed for workforce usherstraining</p>
                        <small class="text-muted">2 Minutes ago</small>
                    </div>
                </div>
            </div>
        </div>

        <!-- END OF RECENT UPDATES -->
        <div class="quick-action">
            <h2>Quick Action</h2>
            <div class="item online">
                <div class="icon">
                 <span class="material-symbols-outlined">person</span>
                </div>
                <div class="right">
                    <div class="info">
                       <a href="{{url_for('members_bp.admin_add')}}">ADD MEMBER</a> 
                        <small class="text-muted"><br> lorem lorem</small>
                    </div>
                    <h5 class="success">+39%</h5>
                    <h3>100</h3>
                </div>
            </div>
            <div class="item offline">
                <div class="icon">
                    <span class="material-symbols-outlined">edit_off</span>
                </div>
                <div class="right">
                    <div class="info">
                        <a href="#">EDIT MEMBER DETAIL</a>
                        <small class="text-muted"><br> lorem lorem</small>
                    </div>
                    <h5 class="success">+39%</h5>
                    <h3>100</h3>
                </div>
            </div>
            <div class="item line">
                <div class="icon">
                    <span class="material-symbols-outlined">send</span>
                </div>
                <div class="right">
                    <div class="info">
                        <a href="#">CREATE MESSAGE TEMPLATES</a>
                        <small class="text-muted"><br> lorem lorem</small>
                    </div>
                    <h5 class="success">+39%</h5>
                    <h3>100</h3>
                </div>
            </div>
        </div>

    </div>
    <script src="{{url_for('static', filename='assets/js/script.js')}}"></script>
</body>
</html>

church-management-frontend/API/templates/layout3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='assets/css/style.css')}}">
    <title>Document</title>
</head>
<body>
    <header>
        <nav class="navbar bg-body-tertiary fixed-top">
          <div class="container-fluid">
            <a href="{{url_for('index_bp.index')}}" class="jesus-pavilion-link"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="primary" class="bi bi-caret-left-fill" viewBox="0 0 16 16">
                <path d="m3.86 8.753 5.482 4.796c.646.566 1.658.106 1.658-.753V3.204a1 1 0 0 0-1.659-.753l-5.48 4.796a1 1 0 0 0 0 1.506z"/>
              </svg></i>
              Jesus Pavilion
            </a>
            <a class="navbar-brand" href="{{url_for('index_bp.index')}}"><img src="{{url_for('static', filename='assets/img/rccgjp_logo.jpg')}}"  height="75px" alt="Logo"></a>
          </div>
        </nav>
      </header>
      {% block content %}

      {% endblock%}
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
    </html>