church-management-frontend/API/MEMBERS/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify, current_app, json, session

members_bp = Blueprint("members_bp", __name__, template_folder='templates', static_folder='static')


@members_bp.route("/members", methods=["POST", "GET"])
def member_section():
    
    return render_template('member/members.html')

@members_bp.route("/add_member_form", methods=["POST", "GET"])
def admin_add():
    return render_template('member/add_member_form.html')

@members_bp.route("/view_member", methods=["POST", "GET"])
def admin_view():
    #members = Member.query.all()  # This retrieves all records from the Member table
    
    return render_template('member/view_member.html')
    # return render_template('member/view_member.html', members=members)

church-management-frontend/API/MEMBERS/templates/member/add_member_form.html
{% extends "layout.html" %}
{% block title %}
Add Member
{% endblock %}
{% block content %}
<div class="form-main-wrapper">
    <div class="form-wrapper">
      <img src="{{url_for('static', filename='assets/img/signimg.png')}}">
      <form action="add_member" method="POST">
        <h1>MEMBER REGISTRATION FORM</h1>
        <!-- Name -->
        <div class="form-group">
          <label for="firstname" class="form-label">First Name</label>
          <input type="text" name="firstname" id="firstname" placeholder="First name" class="form-input" />
        </div>
        <div class="form-group">
          <label for="lastname" class="form-label">Last Name</label>
          <input type="text" name="lastname" id="lastname" placeholder="Last name" class="form-input" />
        </div>
  
        <!-- Date of Birth -->
        <div class="form-group">
          <label for="dob" class="form-label">Date of Birth</label>
          <input type="date" name="dob" id="dob" class="form-input" />
        </div>
  
        <!-- Phone No -->
        <div class="form-group">
          <label for="phone" class="form-label">Phone No</label>
          <input type="text" class="form-input" id="phone" name="phone" placeholder="Number must be 11" required>
        </div>
  
        <!-- Email -->
        <div class="form-group">
          <label for="email" class="form-label">Email</label>
          <input class="form-input" type="email" id="email" name="email" placeholder="example@email.com" required>
        </div>
  
        <!-- Address -->
        <div class="form-group">
          <label for="address-line1" class="form-label">Address</label>
          <input type="text" class="form-input" id="address-line1" name="address-line1" placeholder="Street Address Line " required>
        </div>
  
        <!-- Postcode and City -->
        <div class="form-group input-flex">
          <div>
            <label for="post" class="form-label">Post code</label>
            <input type="text" name="post" id="post" placeholder="ex: NW1 4NP" class="form-input" />
          </div>
          <div>
            <label for="city" class="form-label">City</label>
            <input type="text" name="city" id="city" placeholder="ex: London" class="form-input" />
          </div>
        </div>
  
        <!-- Occupation -->
        <div class="form-group">
          <label for="occupation" class="form-label">Occupation</label>
          <input type="text" class="form-input" id="occupation" name="occupation" placeholder="Enter Your Occupation">
        </div>
  
        <!-- Date Joined Church -->
        <div class="form-group">
          <label for="date" class="form-label">Date Joined Church</label>
          <input type="text" class="form-input" id="date" name="date_joined" placeholder="Please input date (dd/mm/yyyy)" required>
        </div>
  
        <!-- Communication Preferences -->
        <div class="form-group">
          <label for="preferences" class="form-label">Communication Preferences</label>
          <select class="form-input" name="preferences" id="preferences">
            <option value="emailp">Email</option>
            <option value="phonep">Phone</option>
            <option value="smsp">SMS</option>
          </select>
        </div>
  
        <!-- Membership Status -->
        <div class="form-group">
          <label for="membership_status" class="form-label">Membership Status</label>
          <select class="form-input" name="membership_status" id="membership_status">
            <option value="newm">New Member</option>
            <option value="existinm">Existing Member</option>
            <option value="transferm">Transfer Member</option>
          </select>
        </div>
  
        <!-- Parish Name (Conditional) -->
        <div class="form-group">
          <label for="parish-name" class="form-label">If Transfer Member, Enter The Name Of Parish and Year of Attendance</label>
          <input type="text" class="form-input" id="parish-name" name="parish-name">
        </div>
  
        <!-- Submit Button -->
        <button class="form-btn">Submit</button>
      </form>
    </div>
  </div>
{% endblock %}

church-management-frontend/API/MEMBERS/templates/member/members.html
{% extends "layout.html" %}
{% block title %}
Members
{% endblock %}
{% block content %}
         <main>
            <h1>Member Onboarding</h1>
            <div class="date">
                <input type="date">
            </div>

            <a href="{{ url_for('members_bp.admin_view') }}" class="card-link">
                <div class="card-container">
                  <div class="card-content">
                    <div class="card-header">
                      <div class="card-title-section">
                        <h2 class="card-title">Access Member information</h2>
                      </div>
                    </div>
                    <small class="card-text-muted">Click here to access information of your members</small>
                  </div>
                </div>
            </a>

            <a href="{{ url_for('members_bp.admin_add') }}" class="card-link">
                <div class="card-container">
                  <div class="card-content">
                    <div class="card-header">
                      <div class="card-title-section">
                        <h2 class="card-title">Add New Member</h2>
                      </div>
                    </div>
                    <small class="card-text-muted">Click to manually add a new member</small>
                  </div>
                </div>
            </a>

            <a href="{{ url_for('members_bp.admin_add') }}" class="card-link">
                <div class="card-container">
                  <div class="card-content">
                    <div class="card-header">
                      <div class="card-title-section">
                        <h2 class="card-title">Update Member information</h2>
                      </div>
                    </div>
                    <small class="card-text-muted">Update Exiting members information</small>
                  </div>
                </div>
            </a>


                   
              

         </main>
        <!-- END OF MAIN -->

{% endblock %}

church-management-frontend/API/MEMBERS/templates/member/view_member.html
{% extends "layout.html" %}
{% block title %}
Members
{% endblock %}
{% block content %}
         <main>
            <h1>Member Onboarding</h1>
            <div class="date">
                <input type="date">
            </div>
            
            <div class="recent-onboard">
                <h2>Members Table</h2>
                <table>
                    <thead>
                        <tr>
                            <th>MemberID</th>
                            <th>first Name</th>
                            <th>last Name</th>
                            <th>Dob</th>
                            <th>Phone Number</th>
                            <th>Email</th>
                            <th>Address</th>
                            <th>Postcode</th>
                            <th>City</th>
                            <th>Occupation</th>
                            <th>Date Joined</th>
                            <th>Communication</th>
                            <th>Status</th>
                            <th>Parish Name</th>
                            <th>Year Attended</th>
                        </tr>
                    </thead>
                    <tbody>

                        <tr>
                            <td>31013376</td>
                            <td>Fidele </td>
                            <td>Iboh</td>
                            <td>Dob</td>
                            <td>01/01/01</td>
                            <td>07546585856</td>
                            <td>lespatar@gmail.com</td>
                            <td>99 luscinia view napier road</td>
                            <td>builder</td>
                            <td>reading</td>
                            <td>12/08/24</td>
                            <td>email</td>
                            <td>--</td>
                            <td>--</td>
                            <td class="warning">Pending</td>
                        </tr>
                        <!-- Loop through the members and display the data in table rows -->
                        <!-- {% for member in members %}
                        <tr>
                            <td>{{ member.id }}</td>
                            <td>{{ member.full_name }}</td>
                            <td>{{ member.dob }}</td>
                            <td>{{ member.phone }}</td>
                            <td>{{ member.date_joined }}</td>
                            <td>{{ member.time_joined }}</td>
                            <td>{{ member.status }}</td>
                        </tr>
                        {% endfor %} -->
                    </tbody>
                </table>
             </div>
         </main>
        <!-- END OF MAIN -->

{% endblock %}